version: '2'
services:
  node1:
    build: ./node1
    volumes:
      - ../:/rbshark
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - rbshark_net
  node2:
    build: ./node2
    volumes:
      - ../:/rbshark
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - rbshark_net
networks:
  rbshark_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.0.0/24
        - subnet: 2001:db8:10::/64
          gateway: 2001:db8:10::1
